# Site metadata
keywords: Cryptography, Privacy, Information Security, Digital Signatures
description: Academic Website of David Derler
title: Homepage of David Derler

author: Manu Drijvers
authorimg: images/manu.png
authoroccup: Researcher in Cryptography

inst: DFINITY
insturl: https://dfinity.org
uni: DFINITY
uniurl: https://dfinity.org

vcard: 'mailto:manu@ddfinity.org'
twitter: manudrijvers
linkedin: drijvers
dblp: hd/d/Drijvers:Manu
scholar: yWviyh0AAAAJ

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
collections:
  - preprints
  - proc
  - jour
  - articles
  - theses
  - deli
  - talk
exclude:
  - Gemfile
  - Gemfile.lock
