# Site metadata
description: Academic Website of Manu Drijvers
title: Manu Drijvers

author: Manu Drijvers
authorimg: images/manu2.jpg
authoroccup: Researcher in Cryptography

inst: DFINITY
insturl: https://dfinity.org
uni: DFINITY
uniurl: https://dfinity.org

vcard: 'mailto:manu@dfinity.org'
twitter: manudrijvers
linkedin: drijvers
dblp: hd/d/Drijvers:Manu
scholar: yWviyh0AAAAJ

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
collections:
  - preprints
  - proc
  - jour
  - articles
  - theses
  - deli
  - talk
exclude:
  - Gemfile
  - Gemfile.lock
